### PR TITLE
Issue 396 – Add wp-cli instructions to readme

### PR DESCRIPTION
**Pull request by WilliamLeeks**
## Description
As per [Issue 396](https://github.com/DekodeInteraktiv/project-base/issues/396), this PR adds some readme instructions for a workaround to get wp-cli working with Local by Flywheel.

### CODE REVIEW

**Review by walbo — APPROVED** [review]

**Comment by walbo** [comment]
🚀

**Comment by WilliamLeeks** [comment]
@walbo Just seen in the issue that this might be better added in `instructions.md`? Shall I move it?

**Comment by walbo** [comment]
Yeah, think that makes more sense. I guess you mean `INST`

**Comment by WilliamLeeks** [comment]
@walbo Moved.

**Review by walbo — APPROVED** [review]
Thanks for the quick follow-up 👍 

Ship it 🚀

**Pull request merged**
