### PR TITLE
Update .nvmrc

### PR DESCRIPTION
**Pull request by pdewouters**
We can use node 19 https://github.com/WordPress/gutenberg/pull/47490

### CODE REVIEW

**Comment by pdewouters** [comment]
I think using the latest stable version is fine because our use case is for front end use, rather than backend node server which is more critical

**Comment by PeterBooker** [comment]
Potentially relevant, but I do not think non-LTS versions are permanently cached in the `actions/setup-node` action. Which means that using 19 instead of 18 will occasionally cause workflows to take an extra 4-6 minutes downloading the node version. Perhaps we could fix that, but I am uncertain.

Here is an example:
image


What is the advantage of node 19 over node 18 for our use cases and is it worth the increased minutes usage for us and anyone else using project-base?

**Comment by PeterBooker** [comment]
Due to my recent (PR)[#458] changing how we define/use the node version, this will need to update the node version in `package.json` too (oh, and the `README.md` requirements).

**Comment by walbo** [comment]
I'm going to close this one since v19 is already past end-of-life. The current v18 is supported until 2025-04-30

**Pull request closed without merging**
