### PR TITLE
Theme refactor

### PR DESCRIPTION
**Pull request by olethomas**
Simplify logic. Remove all the hooks. Bring back if needed on demand

### CODE REVIEW

**Review by walbo — APPROVED** [review]
LGTM

**Comment by Clorith** [comment]
Big fan of this move, the extensive use of hooks here, although nice in theory, has made it a bit confusing trying to find out where code comes from in the past.

👍

**Comment by zpaceinvader** [comment]
Looks very good!

**Review by zpaceinvader — APPROVED** [review]

**Comment by walbo** [comment]
@stian-overasen Noen tanker rundt denne?

**Review by stian-overasen — APPROVED** [review]

**Pull request merged**
